model: "bert-base-uncased"
task: "MNLI"

output_dir: "/Users/au617011/Documents/Thesis-results/" #/home/ucloud/masters-thesis-new/Results
only_subset: True

training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  logging_dir: "logs"
  logging_steps: 100
  evaluation_strategy: "steps"
  save_steps: 100