model: "bert-base-multilingual-uncased"
task: "MRPC"

output_dir: "/Volumes/Expansion" #/work/Results
only_subset: False

training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  logging_dir: "logs"
  logging_steps: 10
  evaluation_strategy: "steps"
  save_steps: 10