model: "distilbert-base-uncased"
task: "MNLI"

output_dir: /home/ucloud/masters-thesis-new/Results # "/Users/au617011/Documents/Thesis-results/"
only_subset: False

training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  logging_dir: "logs"
  logging_steps: 50
  evaluation_strategy: "steps"
  save_steps: 50