model: "roberta-base"
task: "MNLI"

timestamp: "2024-08-21_18-42-25"

output_dir: "/Volumes/Expansion" #/work/Results

window: 160 # referring to n_docs, not n_steps!!!
step_cutoff: 5000

training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  logging_dir: "logs"
  logging_steps: 100
  evaluation_strategy: "steps"
  save_steps: 1000